### ISSUE TITLE
PDKeychain is not storing data in swift

### ISSUE THREAD

**Issue by perthcitywebdesign** [carlbrown/PDKeychainBindingsController#17]
Hi there,

I am trying to use the library with swift and objectiveC (mix & match).

Here is my code in the swift file

        var url:NSURL = NSURL(string: shopUrl.text)
        var secureStore: PDKeychainBindings = PDKeychainBindings()
        secureStore.setObject("url", forKey: "shopUrl")
        var usernameSecured:NSString = NSString(string: username.text)
         secureStore.setObject("usernameSecured", forKey: "username")
        var passwordSecured:NSString = NSString(string: password.text)
         secureStore.setObject("passwordSecured", forKey: "password")

Receiving an error "Could not store(Add) string. Error was:-34018". What would be the reason?

Thank you.

**Comment by carlbrown** [comment]
See issue #18. It's reported to be working with Swift (and not just by me).
