### ISSUE TITLE
Integration with CocoaPods

### ISSUE THREAD

**Issue by josipbernat** [carlbrown/PDKeychainBindingsController#19]
Can you create CocoaPods integration? It would make using keychain even more easier :)

**Comment by karlbecker** [comment]
I love this library, and would give a +1 for CocoaPods support!  

@carlbrown , if someone makes another pull request to update the podspec in the CocoaPods repo, would you be okay with that? Would you rather this stay out of CocoaPods altogether, or you just haven't used it so therefore haven't had any desire to keep the version updated in the CocoaPods master repo?

Thanks!

**Comment by carlbrown** [comment]
I'm happy to merge CocoaPods pull requests (that's how it got CocoaPods support in the first place).  I don't use CocoaPods myself (I do mostly agency-type work where my clients dictate the toolchain), so I'm not in a position to feel comfortable trying to add support for something I can't easily test

**Comment by karlbecker** [comment]
Thanks for the feedback, @carlbrown - and hope to see you at 360iDev this year, I just noticed you were a speaker there last year!
