### ISSUE TITLE
Access keychain in background

### ISSUE THREAD

**Issue by naqi** [carlbrown/PDKeychainBindingsController#22]
I was trying to get some info from keychain for a background sync but it kept having issues with nil values until I found out that it needs to be specified as accessibility. 

http://stackoverflow.com/questions/10536859/ios-keychain-not-retrieving-values-from-background

I think this might be what is causing nil values for other people as well. Any plans of exposing that in your library? or do you want me to start on a pull request?

**Comment by naqi** [comment]
nvm, i noticed that it was added to latest release. I will update my Pod

**Comment by lyahdav** [comment]
I'm running into this issue as well. I'm a bit confused about the version numbering on this pod. Cocoapods.org shows there's version 0.0.2 as the latest (released May 2014). When I put that version in my Podfile I get this error:
```
[!] Unable to satisfy the following requirements:

- `PDKeychainBindingsController (~> 0.0.2)` required by `Podfile`
```

According to https://github.com/carlbrown/PDKeychainBindingsController/releases the latest version is 1.0.0, released Jun 24, 2013.

I'm going to change my Podfile to use the github repo on master, but would be nice to get an update to cocoapods.org or a release tag to point to.
