### ISSUE TITLE
Support for Touch ID Storage

### ISSUE THREAD

**Issue by Vortec4800** [carlbrown/PDKeychainBindingsController#24]
It appears that you can store items in the keychain in such a way that when you ask for that item later, it shows the Touch ID prompt before giving you the value for that key. Is there any interest in adding support for Touch ID keychain values to this library?

**Comment by carlbrown** [comment]
The core mission of this repo was just to make it was easy as possible for devs (who already knew how to use NSUserDefaults) to protect their users' privacy by using the Keychain instead.  Adding TouchID would make that core mission more complicated.  So while it's a useful endeavor, I don't think this project is the right place for it.
