### ISSUE TITLE
Not working in iOS 10?

### ISSUE THREAD

**Issue by dhiraj** [carlbrown/PDKeychainBindingsController#25]
This works great in iOS 9.x in latest stable Xcode(7.3.1). The problem happens when I start to run with iOS 10 beta with Xcode 8 beta 3.

For some reason, when I'm trying to read entries saved by ```[[PDKeychainBindings sharedKeychainBindings] objectForKey:@"my_key"]``` a ```nil``` is coming back instead of the expected saved object.

```[[PDKeychainBindings sharedKeychainBindings] setObject:@"stringvalue" forKey:@"my_key"]``` is not reporting or causing any crashes.

**Comment by kyleturner** [comment]
@dhiraj I am also seeing this issue now that I've adopted iOS10 and new Xcode beta. Did you come to a resolution with this? Is there a similar alternative you've found if @carlbrown does not intend on adding support anytime soon?

**Comment by MauriceArikoglu** [comment]
@dhiraj @kyleturner I was able to work around this in my app by adding Keychain Access Groups to the Entitlements file. I turned on the Keychain Sharing switch in the Capabilities section in your test app, and it is working for me as well.

**Comment by dhurley14** [comment]
@MauriceArikoglu This worked for me as well.  Thanks!

**Comment by dhiraj** [comment]
Yes, just turning on the switch for Keychain sharing in the target's capability settings fixes the problem.
