### ISSUE TITLE
Remove all keychain data?

### ISSUE THREAD

**Issue by mattgalloway** [carlbrown/PDKeychainBindingsController#6]
Hey man,

I love your keychain library. It's so easy to implement. I'm working on my first project with keychain and through testing I've realized that the keychain data lives on even though the app is deleted. I'm cache user info and I'm not keeping a list of users outside of the keychain so I don't have a list of keys. I want to delete all of the keychain data so I was expecting a "removeAll" or at least an "allKeys" method that I could use to wipe out the data. 

I started looking at the code and realized it would take me a bit just to follow along and I thought it might be an easy add for you. 

Just a thought. Thanks for the great work!

-M.

**Comment by jaunesarmiento** [comment]
Hi @carlbrown, was this issue resolved? Looks like it hasn't been implemented, or I'm missing something.

**Comment by carlbrown** [comment]
Sorry - closed this with another issue and forgot to copy the text:

The core mission of this repo was just to make it was easy as possible for devs (who already knew how to use NSUserDefaults) to protect their users' privacy by using the Keychain instead. Adding additional features would make that core mission more complicated. So while searching and removing information from the keychain is a useful endeavor, I've decided that I don't think this project is the right place for it.
